implicit cast operators for HttpContextBase, HttpRequestBase, HttpResponseBase
dotnet/systemweb-adapters pull request #143
Opened 2022-08-12 08:02 UTC by sdekock

Issue https://github.com/dotnet/systemweb-adapters/issues/142

Add implicit cast operators for HttpContextBase, HttpRequestBase, HttpResponseBase from and to the equivalent ASP.NET Core types.

2022-08-12 08:02 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/systemweb-adapters?pullRequest=143) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/systemweb-adapters?pullRequest=143) before we can accept your contribution.<br/><br/>:x: sdekock [sign now](https://cla.dotnetfoundation.org/dotnet/systemweb-adapters?pullRequest=143)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/systemweb-adapters?pullRequest=143) it.</sub>

2022-08-24 17:57 UTC, twsouthwick requested changes

2022-08-24 17:57 UTC, twsouthwick commented on src/Microsoft.AspNetCore.SystemWebAdapters/HttpRequestBase.cs
> +        public static implicit operator HttpRequestBase?(HttpRequestCore? request) => request?.GetAdapterBase();
Let's just keep the core->adapter implicit operators

2022-08-24 17:57 UTC, twsouthwick commented on src/Microsoft.AspNetCore.SystemWebAdapters/HttpRequestBase.cs
> +        protected virtual HttpRequestCore Unwrap() => throw new NotImplementedException();
I'd prefer we don't add this for reasons discussed on the issue

2022-08-24 17:58 UTC, twsouthwick commented
@sdekock  I'm fine with the implicit operators to convert to the adapters (the absence of those here is probably an oversight). Would be great to get this into the next release if you can remove the other stuff.

2022-08-24 18:09 UTC, twsouthwick approved these changes
LGTM thanks @sdekock

2022-08-24 23:18 UTC, merged