Add diagnostic to verify virtual directory setup
dotnet/systemweb-adapters pull request #175
Opened 2022-08-26 19:09 UTC by twsouthwick

Virtual directories must be the same between the core and framework app. This may not be obvious to users as they get started, but a number of issues have been filed around this. This change adds a middleware/module to the system that can be opted into via `.AddDiagnostics()` to fail early if this condition is determined.

Fixes #174

2022-08-26 19:46 UTC, gumbarros requested changes
In docs/diagnostics.md
```
# Diagnostics

There is an initial system to help diagnose commone issues that can be opted into. Currently, this is only available on the ASP.NET Framework application
``` 

There is a typo, the correct is "commons" instead of "commone" right?

2022-08-26 20:11 UTC, twsouthwick commented
Removing the diagnostic code for now in favor of going down a more generalized approach for health checks: https://github.com/dotnet/systemweb-adapters/issues/176

2022-08-26 23:14 UTC, gumbarros reviewed
Should we specify the two applications must be on different sites to prevent my issues on #174 ?

**Recomendation**: Ensure your two applications have the same virtual directory path and are hosted on different websites.

2022-08-29 17:54 UTC, twsouthwick commented
@gumbarros good catch. I've updated the recommendation

2022-08-29 19:00 UTC, gumbarros approved these changes

2022-08-30 15:50 UTC, twsouthwick commented
@mjrousos @Tratcher can I get someone with write access to approve this?

2022-08-30 16:41 UTC, Tratcher approved these changes

2022-08-30 16:41 UTC, merged