Full support for CacheDependency and accessors. Closes #26
dotnet/systemweb-adapters pull request #276
Opened 2023-02-03 12:00 UTC by CZEMacLeod

**Full support for CacheDependency and accessors.**
Complete the implementation of `System.Web.Caching.CacheDependency` and provide all the accessors from System.Web implementation.

**Description**
Implement all constructors and features of `System.Web.Caching.CacheDependency`
Add extensions to allow handling various underlying `ChangeMonitor` implementations to surface the `UtcLastModified` property.
Implements `CacheDependencyChangeMonitor` to allow a `CacheDependency` to rely on another item in the Cache.
Adds `Cache` accessor to `HttpContext`, `HttpContextBase`, `HttpContextWrapper`, and `HttpRuntime`
Modifies `HttpRuntimeFactory` to allow getting the Cache implementation
Updates tests to support new `IHttpRuntime` interface member.

Addresses #26

2023-02-03 23:27 UTC, Tratcher commented
Test failure:
```
    Microsoft.AspNetCore.SystemWebAdapters.HttpContextTests.CacheFromServices [FAIL]
      System.InvalidOperationException : HttpRuntime is not available in the current environment
      Stack Trace:
        /_/src/Microsoft.AspNetCore.SystemWebAdapters/HttpRuntime.cs(14,0): at System.Web.HttpRuntime.get_Current()
        /_/src/Microsoft.AspNetCore.SystemWebAdapters/HttpRuntime.cs(25,0): at System.Web.HttpRuntime.get_Cache()
        /_/src/Microsoft.AspNetCore.SystemWebAdapters/HttpContext.cs(45,0): at System.Web.HttpContext.get_Cache()
        /_/test/Microsoft.AspNetCore.SystemWebAdapters.Tests/HttpContextTests.cs(152,0): at Microsoft.AspNetCore.SystemWebAdapters.HttpContextTests.CacheFromServices()
```

2023-02-06 22:32 UTC, Tratcher approved these changes
What's the thread safety model here? I'm a little surprised not to see any locking anywhere.

2023-02-07 09:48 UTC, CZEMacLeod commented
> What's the thread safety model here? I'm a little surprised not to see any locking anywhere.

The Cache implementation is a wrapper around a `System.Runtime.Caching.ObjectCache` implementation (`System.Runtime.Caching.MemoryCache` by default) and all the locking etc. logic would be implemented there.

I don't think any of the code I've added actually requires any specific locking logic, although maybe I've missed a scenario where it would be applicable?

2023-02-09 02:00 UTC, twsouthwick requested changes
Looks great! My main concern is around the use of the static HttpRuntime. I'm fine exposing APIs that were there in ASP.NET Framework, but internally, we shouldn't be using those statics for things but access it through the DI container.

2023-02-09 02:00 UTC, twsouthwick commented on src/Microsoft.AspNetCore.SystemWebAdapters.CoreServices/HttpRuntimeFactory.cs
> +        public abstract string AppDomainAppVirtualPath { get; }
This type itself doesn't need to implement IHttpRuntime, just the stuff that is shared and requires the service provider. The IHttpRuntime can be just added to the DefaultHttpRuntime/IIS

2023-02-09 02:00 UTC, twsouthwick commented on src/Microsoft.AspNetCore.SystemWebAdapters/HttpContext.cs
> +    public Cache Cache => HttpRuntime.Cache;
Please still retrieve it through the service provider - it keeps testing easier

2023-02-09 02:00 UTC, twsouthwick commented on src/Microsoft.AspNetCore.SystemWebAdapters/HttpContextWrapper.cs
> +        public override Cache Cache => HttpRuntime.Cache;
```suggestion
        public override Cache Cache => _context.Cache;
```

2023-02-09 02:00 UTC, twsouthwick commented on test/Microsoft.AspNetCore.SystemWebAdapters.CoreServices.Tests/CacheTests.cs
> +            HttpRuntime.Current = httpRuntime;
Any usage of the HttpRuntime outside of statics themselves should be done through DI so we don't need to set this in tests.

2023-02-09 02:00 UTC, twsouthwick commented on test/Microsoft.AspNetCore.SystemWebAdapters.CoreServices.Tests/CacheTests.cs
> +            HttpRuntime.Current = httpRuntime;
Same as above

2023-02-09 02:00 UTC, twsouthwick commented on test/Microsoft.AspNetCore.SystemWebAdapters.CoreServices.Tests/CacheTests.cs
> +            HttpRuntime.Current = httpRuntime;
same as above

2023-02-09 02:00 UTC, twsouthwick commented on test/Microsoft.AspNetCore.SystemWebAdapters.Tests/HttpContextTests.cs
> -        [Fact]
let's keep this as we want it to come from the services. We can expose it through a static property, but internally we shouldn't rely on it that way

2023-02-10 11:35 UTC, CZEMacLeod commented
> We shouldn't be using those statics for things but access it through the DI container.

It think it was a combination of copying from the original design in net4 and thoughts to performance, as if the hit DI _every time_ we need access to the cache, rather than using a static property that is initialized once from the singleton, it might hurt the performance. 
This would happen e.g. when trying to get an item from the cache, not finding it, then adding it.
https://learn.microsoft.com/en-us/previous-versions/aspnet/xhy3h9f9(v=vs.100)
```cs
string cachedString;
cachedString = (string)HttpRuntime.Cache["CacheItem"];
if (cachedString == null)
{
  cachedString = "Hello, World.";
  HttpRuntime.Cache.Insert("CacheItem", cachedString);
}
```
Where `HttpRuntime` could also be `HttpContext`/`HttpContextBase`.

I have removed this from `BaseHttpRuntime`, and now all the accessor methods always hit DI. I guess if it is an issue, then the cache can be stored in a local variable in code. https://github.com/dotnet/systemweb-adapters/commit/685ce4642311d325cdaac71721f4d2a12bc63d9d#r100106939

2023-02-10 16:50 UTC, twsouthwick approved these changes

2023-02-10 16:50 UTC, twsouthwick commented on test/Microsoft.AspNetCore.SystemWebAdapters.CoreServices.Tests/CacheTests.cs
> +            // Assert
```suggestion
            // Assert
            Assert.Same(cache, result);
```

2023-02-10 16:50 UTC, twsouthwick commented on src/Microsoft.AspNetCore.SystemWebAdapters.CoreServices/HttpRuntimeFactory.cs
> +        public Cache Cache => serviceProvider.GetRequiredService<Cache>();
```suggestion
        protected BaseHttpRuntime(IServiceProvider serviceProvider)
        {
            Cache = serviceProvider.GetRequiredService<Cache>();
        }

        public Cache Cache { get; }
```

2023-02-10 16:50 UTC, twsouthwick commented on src/Microsoft.AspNetCore.SystemWebAdapters.CoreServices/HttpRuntimeFactory.cs
> +        public Cache Cache => serviceProvider.GetRequiredService<Cache>();
I'm fine with caching the cache ( :) ), but it's still being accessed via the DI system initially

2023-02-11 00:26 UTC, merged